- name: Create deb packages from installed server
  hosts: all
  sudo: True
  gather_facts: False
  vars_files:
    - roles/common/defaults/main.yml
    - roles/nginx/defaults/main.yml
    - roles/supervisor/defaults/main.yml
    - roles/edxapp/defaults/main.yml
    - roles/analytics-api/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/mongo/defaults/main.yml
  roles:
    - create_pkg
