---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role create_pkg
#

#
# vars are namespace with the module name.
#
create_pkg_role_name: create_pkg
create_pkg_script_dir: "{{ COMMON_APP_DIR }}/create_pkg"

#
# OS packages
#

create_pkg_debian_pkgs:
  - ruby-dev
  - rubygems
# global excludes
create_pkg_excludes:
  - '**/.git'
  - '*.pyc'

create_pkg_local_server_debian_pkgs:
  - python-mysqldb
  - mysql-server-5.5
  - postfix
  - memcached
